-- AGGREGATE FUNCTION & NUMERIC FUNCTION  IN SQL 30 APRIL  --

SELECT * FROM customers;
select * from orders;

-- alias name is temp. name given to a column,table and it is represented with as keywords --
 
-- to calculate the total price of orders -- 
select sum(price) AS Total_Price from orders; 

-- to calculate the average price of orders --
SELECT AVG(PRICE) AS AVG_PRICE FROM ORDERS;

-- TO CALCULATE THE MINIMUM PRICE OF ORDERS --
SELECT MIN(PRICE) AS MINIMUM_PRICE FROM ORDERS;

-- TO CALCULATE THE MAXIMUM PRICE OF ORDERS --
SELECT MAX(PRICE) AS MAXIMUM_PRICE FROM ORDERS;

-- TO CALCULATE THE TOTAL RECORDS FROM ORDERS -- 
SELECT COUNT(PRICE) AS COUNT_PRICE FROM ORDERS;

-- ROUNDOFF --
-- USE ROUND() --

SELECT ROUND(356.45) AS ROUNDOFF FROM DUAL;
SELECT ROUND(356.55) AS ROUNDOFF FROM DUAL;

-- CEIL AND FLOOR --
SELECT CEILING(356.45) AS CEILVALUE FROM DUAL;
SELECT CEIL(356.45) AS CEILVALUE FROM DUAL;

SELECT FLOOR(356.85) AS FLOORVALUE FROM DUAL;

use ds_batch;

SELECT * FROM ORDERS;
SELECT * FROM CUSTOMERS;

-- LENGTH FUN:-
SELECT ONAME, LENGTH(ONAME) AS ONAME_LEN FROM ORDERS;

-- UPPERCASE (U CASE )
SELECT ONAME, UPPER(ONAME) AS UPPER_NAME  FROM ORDERS;

-- LOWER CASE ( L CASE )
SELECT *, LOWER (ONAME) AS LOWERCASE FROM ORDERS;

-- power () is used to calculate power of no. --

SELECT POWER (2,4) AS POWERNO FROM DUAL;

-- SQRT USED TO FIND SQRT OG GIVEN NUMBERS

SELECT sqrt(144)  from dual;

